apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  labels:
    app: persondb
spec:
  type: ClusterIP
  selector:
    app: persondb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: mysql-port
